// 画面の回帰テスト用の最小データ。実データやバックエンドには接続しない。
export const project = {
  id: 'p_test',
  name: 'テスト案件',
  source_key: 'fixture',
  format: 'gpt_direct_image_extraction',
  analysis_path: 'C:/tmp/analysis.json',
  analysis_sha256: 'abc123',
  manifest_path: 'C:/tmp/manifest.json',
  image_root: 'C:/tmp/images',
  created_at: '2026-09-15T22:00:00+09:00',
  item_count: 2,
  status_counts: { unconfirmed: 2, on_hold: 0, confirmed: 0, needs_recheck: 0 },
  ingest_report: {
    source_label: 'テスト案件',
    detected_format: 'gpt_direct_image_extraction',
    analysis_path: 'C:/tmp/analysis.json',
    analyzed_item_count: 2,
    image_missing_count: 0,
    image_missing: [],
    warning_counts: {},
    structure_warnings: [],
    manifest_pages: [],
    manifest_frame_total: 2,
    frames_without_analysis_count: 0,
    scope_note: '解析済み対象だけの一覧。',
  },
}

function row(id: string, marker: string, name: string) {
  return {
    id,
    ordinal: 0,
    marker,
    management_symbols: [marker],
    name,
    name_origin: 'drawing' as const,
    category: 'ダウンライト',
    source_file: 'sampleT.pdf',
    page: 1,
    item_no: 1,
    status: 'unconfirmed' as const,
    status_label: '未確認',
    quantity_status: 'unconfirmed' as const,
    quantity_status_label: '数量未確認',
    relation_status: 'single' as const,
    relation_label: '品番1件',
    relation_hint: 'single',
    entry_count: 1,
    decided_count: 0,
    adopted: [],
    searched_entries: 1,
    candidate_total: 1,
    candidate_returned: 1,
    candidate_truncated: false,
    has_image: true,
    image_missing: [],
    warning_count: 0,
    quantity_value: null,
    quantity_unit: null,
    updated_at: null,
  }
}

export const items = [row('i_one', 'A401', 'ダウンライト'), row('i_two', 'A402', 'ベースライト')]

export function itemDetail(id: string) {
  const marker = id === 'i_one' ? 'A401' : 'A402'
  return {
    id,
    project_id: project.id,
    ordinal: 0,
    source_file: 'sampleT.pdf',
    page: 1,
    item_no: 1,
    display: {
      marker,
      management_symbols: [marker],
      name: 'ダウンライト',
      name_origin: 'drawing',
      category_raw: 'ダウンライト',
      category_normalized: 'ダウンライト',
      manufacturer: null,
    },
    relation: { hint: 'single', status: 'single', evidence: ['品番は1件'] },
    relation_label: '品番1件',
    fields: [],
    quantity: { value: null, unit: null, raw: null, origin: 'unknown' },
    images: {
      item: 'items/item.png',
      item_original: null,
      item_enhanced: null,
      item_binary: null,
      page: null,
      page_width: null,
      page_height: null,
      bbox_pixels: null,
      missing: [],
      available: ['item'],
    },
    warnings: [],
    raw_text: '',
    recognition_notes: [],
    normalized_notes: [],
    uncertain_fields: [],
    source_json: {},
    entries: [
      {
        suffix: 'e00',
        label: '主品番',
        role: 'primary',
        kind: 'code',
        code: 'XLX460DHNK LE9',
        code_raw: 'XLX460DHNK LE9',
        code_note: null,
        hinban: 'XLX460DHNK',
        kidou: 'LE9',
        public_codes: [],
        group: null,
        source_field: 'identity.full_model_number[0]',
        notes: [],
        decision: {
          decision: 'undecided',
          adopted_record_id: null,
          adopted_code: null,
          adopted_summary: null,
          adopted_search_id: null,
          adopted_input_fingerprint: null,
          decision_input_fingerprint: null,
          note: null,
          updated_at: null,
        },
        decision_label: '未判断',
        search: null,
        current_input: {},
        current_input_fingerprint: 'fp',
        effective_identifier: { code: 'XLX460DHNK LE9', hinban: 'XLX460DHNK', kidou: 'LE9', notes: [] },
        decision_stale: false,
      },
    ],
    review: {
      item_id: id,
      status: 'unconfirmed',
      status_label: '未確認',
      quantity_status: 'unconfirmed',
      quantity_status_label: '数量未確認',
      relation_status: 'single',
      quantity_value: null,
      quantity_unit: null,
      corrections: {},
      hold_reason: null,
      memo: null,
      revision: 0,
      updated_at: null,
    },
    history: [],
  }
}
